#!/bin/sh -eu

readonly PROGRAM="pipe"
readonly VERSION="0.2.0"

MODE=client
PIDFILE=/tmp/pipe.pid
LOCKNAME=/tmp/pipe.lock
SYNC=true
BLOCK=true

readonly SUCCESS=0
readonly FAILURE=1

# shellcheck disable=SC2059
errorf() {
  fmt="$1"; shift
  printf "err: ${fmt}" "$@"
}

errorfln() {
  fmt="$1"; shift
  errorf "${fmt}\n" "$@"
}

error() { errorfln '%s' "$*"; }

fatalf()   { errorf   "$@"; exit $FAILURE; }
fatalfln() { errorfln "$@"; exit $FAILURE; }
fatal()    { error    "$@"; exit $FAILURE; }

print_version() { echo "${PROGRAM} v${VERSION}"; }

print_usage() {
cat <<EOF
usage: pipe <MODE> [OPTIONS...]

MODE:
  -i, --input         Spawn the input end of the pipe (default)
  -o, --output        Spawn the output end of the pipe

OPTIONS:
  -n, --name NAME     Name of the pipe
      --no-sync       Don't synchronize writes
  -s, --sync          Synchronize writes (default)
  -u, --non-blocking  Exit if unable to write
  -b, --blocking      Block until able to write (default)

  -h, --help          Print this help.
  -V, --version       Print the version information
EOF
}

requires() {
  command -v "$1" >/dev/null || fatal "required command '${1}' not found in PATH"
}

get_value() {
  # Test if $2 is set; if so, return it
  [ -z "${2+_}" ] || { echo "$2"; return $SUCCESS; }

  # Test if $1 is of the form --key=; if so return an empty string
  [ "$1" = "${1%=}" ] || return $SUCCESS

  # Test if $1 is of the form --key=value; if so return value
  _value="$(
    echo "$1" | {
      IFS='=' read -r _key _value
      [ -z "$_value" ] || { echo "$_value"; return $SUCCESS; }
    }
  )"
  [ -z "$_value" ] || { echo "$_value"; return $SUCCESS; }
  
  fatal "a value must be provided for '${1}'" >&2
}
  
parse() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
    -h|--help)
      print_usage
      exit $SUCCESS
      ;;
    -V|--version)
      print_version
      exit $SUCCESS
      ;;
    -i|--input)  MODE=client ;;
    -o|--output) MODE=server ;;
    -n|--name|--name=*)
      _name="$(get_value "$@")" 2>&1
      PIDFILE="/tmp/pipe-${_name}.pid"
      LOCKNAME="/tmp/pipe-${_name}.lock"
      shift
      ;;
    -s|--sync) SYNC=true ;;
    --no-sync) SYNC=false ;;
    -u|--non-blocking) BLOCK=false ;;
    -b|--blocking)     BLOCK=true ;;
    *)
      errorf "unrecognized argument: '%s'\n\n" "$1"
      print_usage
      exit $FAILURE
      ;;
    esac

    shift
  done
}

cleanup() {
  ! [ "$MODE" = "server" ] || {
    ! [ -f "$PIDFILE"  ] || unlink "$PIDFILE"
    ! [ -f "$LOCKNAME" ] || unlink "$LOCKNAME"
  }
}

main() {
  _pid="$$"

  ! "$SYNC" || requires flock

  parse "$@"

  case "$MODE" in
    server)
      [ ! -e "$PIDFILE" ] || fatal "'${PIDFILE}' already exists"

      trap exit    INT TERM
      trap cleanup EXIT

      echo "$_pid" > "$PIDFILE"
      cat
      ;;
    client)
      [ -e "$PIDFILE" ] || fatal "'${PIDFILE}' doesn't exist"
      _pid="$(cat "$PIDFILE")"
      _stdin="/proc/${_pid}/fd/0"

      "$SYNC" || {
        cat > "$_stdin"
        return
      }

      if "$BLOCK"
      then flock    "$LOCKNAME" cat > "$_stdin"
      else flock -n "$LOCKNAME" cat > "$_stdin"
      fi
      ;;
  esac
}

main "$@"
